apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: A sample service exposing metrics
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
    prometheus.io/alert: 'all'
spec:
  type: service
  owner: team-a
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  annotations:
    prometheus.io/rule: 'example-service'
    prometheus.io/url: 'http://localhost:9090'
spec:
  type: service
  lifecycle: production
  owner: your-team
