apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: A sample service exposing metrics
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
    prometheus.io/alert: 'all'
    prometheus.io/targets: micro-eh-pwe-aks, micro-eh-awe-aks
    prometheus.io/urls: |
      [
        { "name": "dev", "url": "http://localhost:9091" },
        { "name": "prod", "url": "http://localhost:9092" }
      ]
spec:
  type: service
  owner: team-a
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  annotations:
    prometheus.io/url: 'http://localhost:9090'
    prometheus.io/rule: 'process_virtual_memory_bytes|job, process_open_fds|job'
    prometheus.io/alert: 'all'
    prometheus.io/targets: micro-eh-pwe-aks, micro-eh-awe-aks
    prometheus.io/urls: |
      [
        { "name": "dev", "url": "http://localhost:9091" },
        { "name": "prod", "url": "http://localhost:9092" }
      ]
spec:
  type: service
  lifecycle: production
  owner: your-team
